[package]
name = "yaydl"
version = "0.2.2"
authors = ["Cthulhux <git@tuxproject.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.2"
indicatif = "0.15.0"
inventory = "0.1.9"
qstring = "0.7.2"
regex = "1.4.1"
reqwest = { version = "0.10.8", features = ["blocking"] }
serde_json = "1.0"
